server:
  port: 43376

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/providers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: java-order-service
          uri: lb://java-order-service
          predicates:
            - Path=/java/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
